### ISSUE TITLE
Python bindings do not respect non-contiguous NumPy arrays

### ISSUE THREAD

**Issue by ntw-au** [Jaybro/pico_tree#19]
When the Python `pico_tree.KdTree` constructor is passed a non-contiguous NumPy array, such as the result of a `swapaxes` operation, the `KdTree` is constructed with `sdim` and `npts` swapped compared to the expected values. It seems that `KdTree` is not respecting the array strides, but instead is assuming that the array contains a simple block of memory in C-order.

Repro follows:

```python
import pico_tree as pt
import numpy as np

B, N = 2, 1024
knn = 16

xyz = np.random.randn(B, 3, N)
idx = np.broadcast_to(np.arange(knn, dtype=np.int64).reshape(1, 1, knn), (B, N, knn))
points = np.random.randn(B, 8, N)
xyz_p = np.swapaxes(xyz, 2, 1)
xyz_p_contiguous = np.ascontiguousarray(xyz_p)

assert xyz_p.shape == xyz_p_contiguous.shape

contiguous_tree = pt.KdTree(xyz_p_contiguous[0], pt.Metric.L2Squared, 10)
assert contiguous_tree.sdim == 3
assert contiguous_tree.npts == N

noncontiguous_tree = pt.KdTree(xyz_p[0], pt.Metric.L2Squared, 10)
assert noncontiguous_tree.sdim == 3  # Fails, sdim and npts are swapped
assert noncontiguous_tree.npts == N

```

`xyz_p` and `xyz_p_contiguous` contain the same data and act the same using NumPy operations, but the strides are different as `xyz_p` is non-contiguous. The `KdTree` built with the non-contiguous array has `npts == 3` and `sdim == 1024`, the opposite to what is expected, whereas the tree built with the contiguous array works as expected.

A workaround is to ensure that arrays are contiguous before passing to `pico_tree.KdTree`.

**Comment by Jaybro** [comment]
It is true that PicoTree's Python bindings only accept contiguous arrays as an input and an error is raised when a non-contiguous array is used as an argument. This is by design because contiguous arrays provide better performance than non-contiguous ones. Within these contiguous arrays, also for performance, it is expected that the coordinates of a point are aligned in memory. These requirements mean, that if `p.flags.c_contiguous == True`, points must be stored in the rows of a matrix represented by a numpy array. If `p.flags.f_contiguous == True`, points must be stored in the columns.

While `xyz_p` is non-contiguous, `xyz_p[0]` is Fortran contiguous. This 2d array is interpreted as having 3 points, each of which having a spatial dimension of 1024:

```python
B, N = 2, 1024

xyz = np.random.randn(B, 3, N)
xyz_p = np.swapaxes(xyz, 2, 1)
assert xyz_p.flags.contiguous == False
assert xyz_p[0].flags.f_contiguous == True

# PicoTree doesn't raise an error and assumes points are stored in the
# columns of the matrix because of its memory alignment requirements.
tree = pt.KdTree(xyz_p[0], pt.Metric.L2Squared, 10)
assert tree.sdim == N
assert tree.npts == 3

# Raises a non-contiguous array error (points are no longer aligned in
# memory because of the step).
tree = pt.KdTree(xyz_p[0][0:3:2], pt.Metric.L2Squared, 10)
```

Hope this clarifies the behavior of the library.
